export const dataTypes = {
  LOAD_DATA: 'LOAD_DATA',
  LOAD_GRAPH_DATA: 'LOAD_GRAPH_DATA',
  CHANGE_CURR: 'CHANGE_CURR',
  LOAD_AVAILABLE_CURRENCIES: 'LOAD_AVAILABLE_CURRENCIES',
  CHANGE_LAST_X_DAYS: 'CHANGE_LAST_X_DAYS'
};

export const newsTypes = {
  LOAD_NEWS: 'LOAD_NEWS',
  LOAD_HEADLINE_NEWS: 'LOAD_HEADLINE_NEWS'
};
